version: '3.8'
services:
  backend:
    image: rhithanya/in-ctrl-backend:latest
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./data/in-ctrlDb
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.H2Dialect

  frontend:
    image: rhithanya/in-ctrl-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
